version: '3.8'
services:
  mongo1:
    image: mongo:latest
    restart: always
    networks: 
      - mongocluster
    command: --replSet mongo-rs --keyFile /etc/mongo-keyfile --setParameter authenticationMechanisms=SCRAM-SHA-256
    volumes:
      - mongo1-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo2:
    image: mongo:latest
    restart: always
    networks: 
      - mongocluster
    command: --replSet mongo-rs --keyFile /etc/mongo-keyfile --setParameter authenticationMechanisms=SCRAM-SHA-256
    volumes:
      - mongo2-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo3:
    image: mongo:latest
    restart: always
    networks: 
      - mongocluster
    command: --replSet mongo-rs --keyFile /etc/mongo-keyfile --setParameter authenticationMechanisms=SCRAM-SHA-256
    volumes:
      - mongo3-data:/data/db
      - ./mongodb-keyfile:/etc/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

  mongo-init-replica:
    image: mongo:latest
    networks: 
      - mongocluster
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./mongo-init-replica:/docker-entrypoint-initdb.d/
      - ./mongodb-keyfile:/etc/mongo-keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

networks:
  mongocluster:
    driver: bridge

volumes:
  mongo1-data:
  mongo2-data:
  mongo3-data:

